openapi: 3.0.3

info:
  title: Mini E-Commerce API
  version: 1.0.0
  description: >
    Kontrak API untuk Praktikum #4 (Orders & Notifications).
    Pola : API-First -> Mock -> Test -> Implement
  contact:
    name: Praktikum Web Service Engineering
    url: https://example.edu/wse
    email: wse-praktikum@example.edu

servers:
  - url: http://localhost

tags:
  - name: Orders
    description: Endpoint terkait pembuatan dan pengelolaan pesanan
  - name: Notifications
    description: Endpoint terkait daftar notifikasi sistem

paths:
  /orders:
    post:
      tags: [Orders]
      operationId: createOrder
      summary: Create Order
      description: Membuat pesanan baru (in-memory untuk praktikum)
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateOrder'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'

  /Notifications:
    get:
      tags: [Notifications]
      operationId: listNotifications
      summary: List Notifications
      description: Mengembalikan daftar notifikasi terbaru
      security:
        - bearerAuth: []
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 10
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Notification'
                  total:
                    type: integer
        '401':
          $ref: '#/components/responses/Unauthorized'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  responses:
    BadRequest:
      description: Validation error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

  schemas:
    CreateOrder:
      type: object
      required:
        - productId
        - quantity
      properties:
        productId:
          type: string
        quantity:
          type: integer
          minimum: 1

    Order:
      type: object
      properties:
        id:
          type: string
        productId:
          type: string
        quantity:
          type: integer
        createdAt:
          type: string
          format: date-time

    Notification:
      type: object
      properties:
        id:
          type: string
        type:
          type: string
        message:
          type: string
        createdAt:
          type: string
          format: date-time

    Error:
      type: object
      properties:
        message:
          type: string
        code:
          type: string
